import type { Service, Bundle, Testimonial, CaseStudy, FAQ } from './types';

export const services: Service[] = [
  {
    id: 's1',
    slug: 'instagram-post-design',
    name: 'Instagram Post Design',
    tagline: 'Eye-catching posts for your brand',
    description: 'Professional Instagram post designs that stop the scroll and elevate your brand.',
    price: 49,
    deliveryTime: '1-2 days delivery',
    rating: 4.8,
    reviewCount: 1200,
    category: 'Social Media',
    icon: 'Instagram',
    image: '/service-instagram-post-design.webp',
    popular: true,
    included: [
      '5 custom Instagram post designs',
      'Brand color & font matching',
      'High-resolution image files',
      'Source file delivery',
      '1 round of revisions',
    ],
    revisions: '1 revision included',
    whatsNeeded: [
      'Your brand logo & guidelines',
      'Brand color codes (hex)',
      'Preferred fonts',
      'Content or captions for each post',
      'Any reference designs you like',
    ],
    deliverables: [
      '5 ready-to-post Instagram images (1080x1080px)',
      'Source files in Canva or Figma',
      'PNG & JPG formats',
    ],
    longDescription:
      'Our expert designers create scroll-stopping Instagram posts tailored to your brand identity. Each design is crafted to maximize engagement, maintain visual consistency, and drive results. Perfect for brands looking to elevate their Instagram presence with professional, on-brand content.',
  },
  {
    id: 's2',
    slug: 'instagram-reel',
    name: 'Instagram Reel',
    tagline: 'Short videos that get noticed',
    description: 'Engaging Instagram Reels that boost reach and engagement.',
    price: 99,
    deliveryTime: '2-3 days delivery',
    rating: 4.7,
    reviewCount: 980,
    category: 'Social Media',
    icon: 'Video',
    image: '/service-instagram-reel.webp',
    popular: true,
    included: [
      '1 professional Instagram Reel (up to 30s)',
      'Script & storyboard',
      'Professional editing with transitions',
      'Trending audio selection',
      'Captions & text overlays',
      '1 round of revisions',
    ],
    revisions: '1 revision included',
    whatsNeeded: [
      'Your brand logo & guidelines',
      'Raw footage or product images',
      'Key message or promotion details',
      'Target audience description',
      'Any reference Reels you like',
    ],
    deliverables: [
      '1 edited Instagram Reel (1080x1920px)',
      'MP4 format, optimized for Instagram',
      'Caption text file',
    ],
    longDescription:
      'Short-form video is the most powerful tool for Instagram growth. Our Reels are designed to capture attention in the first 3 seconds, deliver your message effectively, and drive engagement. We handle everything from scripting to editing with trending audio.',
  },
  {
    id: 's3',
    slug: 'social-media-management',
    name: 'Social Media Management',
    tagline: 'Plan, create, post & engage',
    description: 'Full-service social media management to grow your presence.',
    price: 299,
    priceSuffix: '/month',
    deliveryTime: '5-7 days delivery',
    rating: 4.6,
    reviewCount: 800,
    category: 'Social Media',
    icon: 'Calendar',
    image: '/service-social-media-management.webp',
    included: [
      '12 posts per month (3 per week)',
      '4 Instagram Reels per month',
      'Content calendar planning',
      'Community management (comments & DMs)',
      'Monthly performance report',
      'Hashtag research & strategy',
    ],
    revisions: '2 revisions per post',
    whatsNeeded: [
      'Access to your social media accounts',
      'Brand guidelines & assets',
      'Business goals & target audience',
      'Preferred posting schedule',
      'List of competitors to monitor',
    ],
    deliverables: [
      'Monthly content calendar',
      '12 designed posts + 4 Reels',
      'Community engagement report',
      'Monthly analytics & insights report',
    ],
    longDescription:
      'A complete social media management solution. We handle strategy, content creation, scheduling, and community engagement so you can focus on running your business. Our team ensures consistent, high-quality content that builds your brand and grows your audience month over month.',
  },
  {
    id: 's4',
    slug: 'google-ads-setup',
    name: 'Google Ads Setup',
    tagline: 'Set up & optimize your campaigns',
    description: 'Professional Google Ads setup to drive qualified traffic.',
    price: 499,
    deliveryTime: '3-5 days delivery',
    rating: 4.8,
    reviewCount: 740,
    category: 'Paid Advertising',
    icon: 'Search',
    image: '/service-google-ads-setup.webp',
    popular: true,
    included: [
      'Full Google Ads account setup',
      'Keyword research (up to 100 keywords)',
      '3 ad groups with 2 ad variations each',
      'Conversion tracking setup',
      'Audience targeting configuration',
      '1 month of optimization',
    ],
    revisions: 'Ongoing optimization for 30 days',
    whatsNeeded: [
      'Website URL & landing pages',
      'Business goals & target CPA',
      'Monthly ad budget',
      'Access to Google Ads account',
      'List of competitors',
    ],
    deliverables: [
      'Fully configured Google Ads account',
      'Keyword strategy document',
      '6+ ad copy variations',
      'Conversion tracking setup',
      '30-day optimization report',
    ],
    longDescription:
      'Get your Google Ads campaigns set up by certified professionals. We handle everything from keyword research to ad copy creation to conversion tracking. Our data-driven approach ensures your budget is spent efficiently, targeting the right audience with compelling ads that drive clicks and conversions.',
  },
  {
    id: 's5',
    slug: 'meta-ads-setup',
    name: 'Meta Ads Setup',
    tagline: 'Reach the right audience',
    description: 'Meta Ads (Facebook & Instagram) setup with precision targeting.',
    price: 499,
    deliveryTime: '3-5 days delivery',
    rating: 4.7,
    reviewCount: 650,
    category: 'Paid Advertising',
    icon: 'Target',
    image: '/service-meta-ads-setup.webp',
    included: [
      'Meta Business Manager setup',
      'Audience research & targeting',
      '3 ad campaigns with creative',
      'Pixel installation & tracking',
      'A/B testing framework',
      '1 month of optimization',
    ],
    revisions: 'Ongoing optimization for 30 days',
    whatsNeeded: [
      'Website URL & landing pages',
      'Access to Meta Business Manager',
      'Brand assets & ad creatives',
      'Monthly ad budget',
      'Target audience description',
    ],
    deliverables: [
      'Fully configured Meta Ads account',
      '3 active campaigns with ad sets',
      'Pixel & conversion tracking setup',
      '30-day optimization report',
    ],
    longDescription:
      'Maximize your reach on Facebook and Instagram with professionally set up Meta Ads. We create precise audience targeting, compelling ad creatives, and robust tracking to ensure every dollar spent drives measurable results. Perfect for businesses looking to scale their social advertising.',
  },
  {
    id: 's6',
    slug: 'seo-audit',
    name: 'SEO Audit',
    tagline: 'Find opportunities & fix issues',
    description: 'Comprehensive SEO audit with actionable recommendations.',
    price: 399,
    deliveryTime: '5-7 days delivery',
    rating: 4.5,
    reviewCount: 540,
    category: 'SEO',
    icon: 'FileSearch',
    image: '/service-seo-audit.webp',
    included: [
      'Full technical SEO audit',
      'On-page SEO analysis',
      'Competitor keyword analysis',
      'Backlink profile review',
      'Core Web Vitals assessment',
      'Prioritized action plan',
    ],
    revisions: '1 revision included',
    whatsNeeded: [
      'Website URL',
      'Google Search Console access',
      'Google Analytics access (optional)',
      'List of target keywords (if any)',
      'Main competitors',
    ],
    deliverables: [
      'Comprehensive SEO audit report (PDF)',
      'Prioritized action plan',
      'Keyword opportunity spreadsheet',
      'Technical issues checklist',
    ],
    longDescription:
      'Our comprehensive SEO audit digs deep into your website to uncover every opportunity for improvement. We analyze technical SEO, on-page factors, content quality, backlinks, and competitor strategies. You receive a prioritized, actionable plan to boost your search rankings and organic traffic.',
  },
  {
    id: 's7',
    slug: 'landing-page-design',
    name: 'Landing Page Design',
    tagline: 'High-converting landing pages',
    description: 'Conversion-optimized landing pages that turn visitors into customers.',
    price: 899,
    deliveryTime: '4-6 days delivery',
    rating: 4.6,
    reviewCount: 460,
    category: 'Web Design',
    icon: 'Layout',
    image: '/service-landing-page-design.webp',
    included: [
      '1 custom landing page design',
      'Mobile-responsive layout',
      'Conversion-optimized copy structure',
      'Wireframe & design mockup',
      'Figma source file',
      '2 rounds of revisions',
    ],
    revisions: '2 revisions included',
    whatsNeeded: [
      'Product or service details',
      'Target audience & goals',
      'Brand guidelines & assets',
      'Preferred examples/references',
      'Call-to-action requirements',
    ],
    deliverables: [
      '1 landing page design (Figma)',
      'Desktop & mobile layouts',
      'Design handoff documentation',
      'Asset files',
    ],
    longDescription:
      'A high-converting landing page is the difference between traffic and revenue. Our designers create visually stunning, conversion-optimized landing pages built on proven frameworks. Every element — from headline to CTA — is strategically placed to guide visitors toward your desired action.',
  },
  {
    id: 's8',
    slug: 'google-business-profile-setup',
    name: 'Google Business Profile Setup',
    tagline: 'Get found on Google Maps',
    description: 'Professional Google Business Profile setup & optimization.',
    price: 249,
    deliveryTime: '2-3 days delivery',
    rating: 4.7,
    reviewCount: 420,
    category: 'SEO',
    icon: 'MapPin',
    image: '/service-google-business-profile-setup.webp',
    included: [
      'Full Google Business Profile setup',
      'Category & service optimization',
      'Business description writing',
      'Q&A section setup',
      'Photo & post guidelines',
      'Review management strategy',
    ],
    revisions: '1 revision included',
    whatsNeeded: [
      'Business name & address',
      'Business hours & contact info',
      'Business photos',
      'List of services offered',
      'Google account access',
    ],
    deliverables: [
      'Fully optimized Google Business Profile',
      'Business description copy',
      'Q&A template',
      'Review management guide',
    ],
    longDescription:
      'Your Google Business Profile is often the first impression customers have of your business. We set up and optimize every element to ensure you rank higher in local search, appear prominently on Google Maps, and convert profile visitors into customers.',
  },
  {
    id: 's9',
    slug: 'content-calendar',
    name: 'Content Calendar',
    tagline: 'Plan your content for the month',
    description: 'Strategic content calendar with post ideas and captions.',
    price: 199,
    deliveryTime: '2-3 days delivery',
    rating: 4.5,
    reviewCount: 300,
    category: 'Content',
    icon: 'CalendarDays',
    image: '/service-content-calendar.webp',
    included: [
      '30-day content calendar',
      'Post ideas for each day',
      'Caption drafts for 15 posts',
      'Hashtag strategy',
      'Content pillar framework',
      '1 revision round',
    ],
    revisions: '1 revision included',
    whatsNeeded: [
      'Brand guidelines & tone of voice',
      'Target audience description',
      'Business goals for the month',
      'Any promotions or launches',
      'Preferred platforms',
    ],
    deliverables: [
      '30-day content calendar (spreadsheet)',
      '15 caption drafts',
      'Hashtag sets by category',
      'Content pillar guide',
    ],
    longDescription:
      'Never wonder what to post again. Our content strategists create a comprehensive 30-day content calendar tailored to your brand, audience, and goals. Each day includes post ideas, caption drafts, and hashtag recommendations to keep your social media consistent and strategic.',
  },
  {
    id: 's10',
    slug: 'graphic-designing',
    name: 'Graphic Designing',
    tagline: 'Stunning visuals for every platform',
    description: 'Custom graphic design for ads, social media, print, and branding.',
    price: 349,
    deliveryTime: '3-5 days delivery',
    rating: 4.6,
    reviewCount: 310,
    category: 'Content',
    icon: 'Image',
    image: '/service-ad-creative-pack.webp',
    included: [
      '10 custom graphic designs (various formats)',
      '5 static ad visuals',
      '3 carousel creatives',
      '2 promotional banners',
      'Brand-consistent styling',
      '1 revision round',
    ],
    revisions: '1 revision included',
    whatsNeeded: [
      'Brand guidelines & assets',
      'Product or service details',
      'Target audience',
      'Preferred platforms (social, print, web)',
      'Any reference designs you like',
    ],
    deliverables: [
      '10 graphic designs in multiple formats',
      'Source files (Figma/Canva)',
      'PNG, JPG & PDF exports',
      'Brand style guide',
    ],
    longDescription:
      'From ad creatives to social media graphics to print collateral, our graphic design service covers every visual your brand needs. We create stunning, on-brand designs that capture attention and communicate your message clearly across every platform — digital, print, and beyond.',
  },
  {
    id: 's11',
    slug: 'ai-image-creation',
    name: 'AI Image Creation',
    tagline: 'Custom AI-generated visuals',
    description: 'Bespoke AI-generated images for marketing, branding, and content.',
    price: 0,
    customPricing: true,
    deliveryTime: '2-4 days delivery',
    rating: 4.9,
    reviewCount: 180,
    category: 'Content',
    icon: 'Sparkles',
    image: '/service-ai-image-creation.webp',
    popular: true,
    included: [
      'Custom AI image generation',
      'Up to 20 high-resolution images',
      'Style matching to your brand',
      'Multiple variations per concept',
      'Commercial usage rights',
      '2 revision rounds',
    ],
    revisions: '2 revisions included',
    whatsNeeded: [
      'Brand guidelines & visual style',
      'Description of desired imagery',
      'Reference images or mood board',
      'Intended use (social, web, print)',
      'Preferred color palette',
    ],
    deliverables: [
      'Up to 20 AI-generated images (4K resolution)',
      'Multiple style variations',
      'Commercial license',
      'Source prompts & settings',
    ],
    longDescription:
      'Harness the power of AI to create unique, high-quality visuals tailored to your brand. Our AI image creation service combines cutting-edge generative models with expert art direction to produce images that are distinctive, on-brand, and ready for commercial use. Perfect for marketing campaigns, social content, product visuals, and creative branding.',
  },
  {
    id: 's12',
    slug: 'ai-video-production',
    name: 'AI Video Production',
    tagline: 'AI-powered video content',
    description: 'Professional AI-generated videos for ads, social, and brand storytelling.',
    price: 0,
    customPricing: true,
    deliveryTime: '3-5 days delivery',
    rating: 4.8,
    reviewCount: 140,
    category: 'Content',
    icon: 'Clapperboard',
    image: '/service-ai-video-production.webp',
    popular: true,
    included: [
      '1 AI-produced video (up to 60s)',
      'Script & storyboard',
      'AI voiceover or music selection',
      'Custom AI-generated visuals',
      'Professional editing & transitions',
      '2 revision rounds',
    ],
    revisions: '2 revisions included',
    whatsNeeded: [
      'Brand guidelines & assets',
      'Video concept or message',
      'Target audience description',
      'Preferred video style (animated, cinematic, etc.)',
      'Any reference videos you like',
    ],
    deliverables: [
      '1 AI-produced video (up to 60s)',
      'MP4 format, optimized for web & social',
      'Script & storyboard document',
      'Thumbnail image',
    ],
    longDescription:
      'Create compelling video content powered by AI. Our AI video production service blends generative AI with professional editing to produce videos that tell your brand story — from concept to final cut. Ideal for product launches, social media ads, explainer videos, and brand films that need to stand out.',
  },
  {
    id: 's13',
    slug: 'web-design-services',
    name: 'Web Design Services',
    tagline: 'Beautiful websites that convert',
    description: 'Custom website design and development for businesses of all sizes.',
    price: 0,
    customPricing: true,
    deliveryTime: '7-14 days delivery',
    rating: 4.8,
    reviewCount: 220,
    category: 'Web Design',
    icon: 'Monitor',
    image: '/service-web-design-services.webp',
    included: [
      'Custom website design (up to 10 pages)',
      'Mobile-responsive layout',
      'SEO-friendly structure',
      'CMS integration (WordPress/Webflow)',
      'Contact forms & lead capture',
      '3 rounds of revisions',
    ],
    revisions: '3 revisions included',
    whatsNeeded: [
      'Business details & goals',
      'Brand guidelines & assets',
      'List of pages needed',
      'Reference websites you like',
      'Content (text & images) or content brief',
    ],
    deliverables: [
      'Fully designed & developed website',
      'CMS setup & training',
      'Mobile-responsive design',
      'On-page SEO setup',
      '30 days post-launch support',
    ],
    longDescription:
      'Your website is your digital storefront. We design and build beautiful, fast, conversion-focused websites that reflect your brand and drive results. From corporate sites to e-commerce, every page is crafted with user experience, SEO, and performance in mind. Get a website that works as hard as you do.',
  },
  {
    id: 's14',
    slug: 'digital-marketing-consulting',
    name: 'Digital Marketing Consulting',
    tagline: 'Expert strategy & guidance',
    description: 'One-on-one consulting to build your digital marketing strategy.',
    price: 499,
    deliveryTime: '1-3 days delivery',
    rating: 4.9,
    reviewCount: 160,
    category: 'Paid Advertising',
    icon: 'Lightbulb',
    image: '/service-digital-marketing-consulting.webp',
    included: [
      '1-hour strategy session (video call)',
      'Full digital marketing audit',
      'Channel strategy recommendations',
      '30-day action plan',
      'Budget allocation guidance',
      'Follow-up email summary',
    ],
    revisions: '1 follow-up call included',
    whatsNeeded: [
      'Business overview & current marketing efforts',
      'Goals & target audience',
      'Monthly marketing budget',
      'Access to analytics (if available)',
      'Key challenges or pain points',
    ],
    deliverables: [
      'Digital marketing audit report',
      'Channel strategy document',
      '30-day action plan',
      'Budget allocation spreadsheet',
      'Session recording & notes',
    ],
    longDescription:
      'Get expert guidance from seasoned digital marketing strategists. Whether you are starting from scratch or looking to scale, our consulting session provides a clear, actionable roadmap tailored to your business. We audit your current efforts, identify growth opportunities, and build a prioritized plan you can execute immediately.',
  },
  {
    id: 's15',
    slug: 'website-auditing-revamping',
    name: 'Website Auditing & Revamping',
    tagline: 'Audit, optimize & redesign',
    description: 'Comprehensive website audit with a full redesign to boost performance.',
    price: 0,
    customPricing: true,
    deliveryTime: '7-14 days delivery',
    rating: 4.7,
    reviewCount: 130,
    category: 'Web Design',
    icon: 'Wrench',
    image: '/service-website-auditing-revamping.webp',
    included: [
      'Full website audit (UX, performance, SEO)',
      'Before & after comparison report',
      'Complete visual redesign',
      'Performance optimization (speed, Core Web Vitals)',
      'Mobile responsiveness fixes',
      '3 rounds of revisions',
    ],
    revisions: '3 revisions included',
    whatsNeeded: [
      'Website URL & CMS access',
      'Business goals & target audience',
      'Analytics access (Google Analytics, Search Console)',
      'List of known issues or complaints',
      'Brand guidelines (if updating)',
    ],
    deliverables: [
      'Comprehensive website audit report',
      'Fully revamped website',
      'Performance optimization report',
      'Before & after comparison',
      '30 days post-launch support',
    ],
    longDescription:
      'Is your website underperforming? Our auditing and revamping service goes beyond a simple redesign. We conduct a thorough audit of your UX, performance, SEO, and conversion paths, then rebuild your site to address every issue. The result is a faster, more beautiful, higher-converting website that aligns with your business goals.',
  },
  {
    id: 's16',
    slug: 'aeo-geo-audit',
    name: 'AEO & GEO Audit',
    tagline: 'Optimize for AI & local search',
    description: 'Answer Engine Optimization and Generative Engine Optimization audit.',
    price: 599,
    deliveryTime: '5-7 days delivery',
    rating: 4.8,
    reviewCount: 90,
    category: 'SEO',
    icon: 'Globe',
    image: '/service-aeo-geo-audit.webp',
    popular: true,
    included: [
      'Answer Engine Optimization (AEO) analysis',
      'Generative Engine Optimization (GEO) review',
      'AI search visibility assessment (ChatGPT, Perplexity, Google AI)',
      'Local SEO & Google Maps optimization check',
      'Structured data & schema audit',
      'Prioritized action plan',
    ],
    revisions: '1 revision included',
    whatsNeeded: [
      'Website URL',
      'Business location & service areas',
      'Google Business Profile access',
      'Target keywords & queries',
      'Main competitors',
    ],
    deliverables: [
      'AEO & GEO audit report (PDF)',
      'AI search visibility scorecard',
      'Local SEO optimization checklist',
      'Structured data recommendations',
      'Prioritized action plan',
    ],
    longDescription:
      'The future of search is AI-powered. Our AEO & GEO audit ensures your business is visible not just in traditional search, but in AI-generated answers from ChatGPT, Perplexity, Google AI Overviews, and voice assistants. We also optimize your local search presence with GEO targeting. Stay ahead of the curve and get found wherever your customers are searching.',
  },
];

export const bundles: Bundle[] = [
  {
    id: 'b1',
    slug: 'starter-social-media-bundle',
    name: 'Starter Social Media Bundle',
    badge: 'Best Value',
    description: '10 Instagram Posts + 5 Reels + 1 Month Management',
    price: 799,
    originalPrice: 1199,
    deliveryTime: '7-10 days delivery',
    rating: 4.6,
    reviewCount: 320,
    items: [
      '10 Instagram Post Designs',
      '5 Instagram Reels',
      '1 Month Social Media Management',
      'Content Calendar',
      'Hashtag Strategy',
    ],
    included: [
      '10 custom Instagram post designs',
      '5 professional Instagram Reels',
      '1 month full social media management',
      'Content calendar planning',
      'Community engagement',
      'Monthly performance report',
    ],
  },
  {
    id: 'b2',
    slug: 'growth-ads-bundle',
    name: 'Growth Ads Bundle',
    description: 'Google Ads Setup + Meta Ads Setup + 1 Month Optimization',
    price: 1299,
    originalPrice: 1799,
    deliveryTime: '7-10 days delivery',
    rating: 4.7,
    reviewCount: 280,
    items: [
      'Google Ads Setup',
      'Meta Ads Setup',
      '1 Month Optimization',
      'Conversion Tracking',
      'A/B Testing Framework',
    ],
    included: [
      'Full Google Ads account setup',
      'Full Meta Ads account setup',
      'Conversion tracking for both platforms',
      '1 month of ongoing optimization',
      'A/B testing framework',
      'Monthly performance report',
    ],
  },
  {
    id: 'b3',
    slug: 'complete-brand-booster',
    name: 'Complete Digital Marketing',
    description: 'All-in-One: Social Media + Ads + SEO + Content Calendar',
    price: 2000,
    originalPrice: 3699,
    deliveryTime: 'Recurring monthly delivery',
    rating: 4.8,
    reviewCount: 190,
    items: [
      'Social Media Management',
      'Google Ads Setup',
      'Meta Ads Setup',
      'SEO Audit',
      'Content Calendar',
      'Landing Page Design',
    ],
    included: [
      '1 month social media management',
      'Google Ads + Meta Ads setup',
      'Comprehensive SEO audit',
      '30-day content calendar',
      '1 custom landing page design',
      'Monthly performance report',
    ],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    quote:
      'Super easy to use and the results are amazing! Our Instagram engagement increased by 3x in just 2 weeks.',
    name: 'Priya Sharma',
    role: 'Small Business Owner, Pune',
    rating: 5,
  },
  {
    id: 't2',
    quote:
      'Loved the transparency and flexibility. No long contracts, just results. Highly recommend Abhiruchi!',
    name: 'Rohan Mehta',
    role: 'Founder, Local Brand',
    rating: 5,
  },
  {
    id: 't3',
    quote:
      'The Google Ads setup was seamless and brought in quality leads within days. Great value for money!',
    name: 'Neha Verma',
    role: 'E-commerce Business',
    rating: 5,
  },
];

export const caseStudies: CaseStudy[] = [
  {
    id: 'c1',
    category: 'Social Media + Ads',
    title: 'Fashion Brand | 3x ROAS',
    description:
      'Combined Meta ads + Instagram content increased sales by 3x in 2 months.',
    metric: '3x ROAS',
    timeframe: 'in 2 months',
  },
  {
    id: 'c2',
    category: 'Google Ads',
    title: 'Restaurant | 65% More Leads',
    description:
      'Google Ads setup & optimization brought in 65% more leads at lower CPA.',
    metric: '65% more leads',
    timeframe: 'in 45 days',
  },
  {
    id: 'c3',
    category: 'SEO',
    title: 'Fitness Studio | Top 3 Rankings',
    description:
      'SEO audit + optimization got them to top 3 for 5 high-intent keywords.',
    metric: '5 keywords',
    timeframe: 'in top 3',
  },
];

export const faqs: FAQ[] = [
  {
    id: 'f1',
    question: 'How long does delivery take?',
    answer:
      'Delivery times vary by service. Most services are delivered within 1-7 days, while bundles may take 7-14 days. Each service page shows the exact delivery timeframe. You will receive updates throughout the process.',
  },
  {
    id: 'f2',
    question: 'Can I get a refund?',
    answer:
      'Yes. If work has not started on your service, you can request a full refund. If work has begun, we offer partial refunds based on progress. Our goal is your complete satisfaction — contact us within 7 days of delivery for any issues.',
  },
  {
    id: 'f3',
    question: 'Do you offer revisions?',
    answer:
      'Absolutely. Every service includes at least 1 round of revisions. Some services include 2 rounds. If you need additional revisions beyond what is included, they can be purchased separately at a nominal rate.',
  },
  {
    id: 'f4',
    question: 'Do you provide reports?',
    answer:
      'Yes. For ongoing services like Social Media Management and Ads Setup, we provide detailed monthly performance reports. For one-time services like SEO Audits, you receive a comprehensive report document.',
  },
  {
    id: 'f5',
    question: 'Are there any hidden charges?',
    answer:
      'No hidden charges, ever. The price you see on each service is the price you pay. Ad spend budgets for Google Ads and Meta Ads are separate and paid directly to the ad platforms — we never mark up your ad budget.',
  },
  {
    id: 'f6',
    question: 'Can I request a custom service?',
    answer:
      'Yes! If you need something not listed in our catalog, simply click "Request Custom Service" and tell us about your goals. Our team will craft a tailored solution and provide a transparent quote within 24 hours.',
  },
];

export const stats = [
  { label: 'Happy Customers', value: '67' },
  { label: 'Average Rating', value: '4.7/5' },
  { label: 'Projects Delivered', value: '144' },
  { label: 'On-Time Delivery', value: '98%' },
];

export const categories = [
  { name: 'Social Media', icon: 'Instagram', count: 3 },
  { name: 'Paid Advertising', icon: 'Target', count: 3 },
  { name: 'SEO', icon: 'Search', count: 3 },
  { name: 'Web Design', icon: 'Layout', count: 2 },
  { name: 'Content', icon: 'PenTool', count: 4 },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getBundleBySlug(slug: string): Bundle | undefined {
  return bundles.find((b) => b.slug === slug);
}

export function getRelatedServices(service: Service, count = 4): Service[] {
  return services
    .filter((s) => s.id !== service.id && s.category === service.category)
    .slice(0, count);
}

export function formatPrice(price: number): string {
  return `$${price.toLocaleString('en-US')}`;
}
